# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 454)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(Form)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.leftFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stateFrame = QtWidgets.QFrame(self.leftFrame)
        self.stateFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stateFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stateFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stateFrame.setLineWidth(0)
        self.stateFrame.setObjectName("stateFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stateFrame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.stateFrame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stateLabel = QtWidgets.QLabel(self.stateFrame)
        self.stateLabel.setObjectName("stateLabel")
        self.gridLayout_2.addWidget(self.stateLabel, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.stateFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.currentSampleLabel = QtWidgets.QLabel(self.stateFrame)
        self.currentSampleLabel.setObjectName("currentSampleLabel")
        self.gridLayout_2.addWidget(self.currentSampleLabel, 1, 1, 1, 1)
        self.setupButton = QtWidgets.QPushButton(self.stateFrame)
        self.setupButton.setObjectName("setupButton")
        self.gridLayout_2.addWidget(self.setupButton, 1, 2, 1, 1)
        self.scanAllButton = QtWidgets.QPushButton(self.stateFrame)
        self.scanAllButton.setObjectName("scanAllButton")
        self.gridLayout_2.addWidget(self.scanAllButton, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.stateFrame, 0, 0, 1, 2)
        self.cassetteList = QtWidgets.QListWidget(self.leftFrame)
        self.cassetteList.setMaximumSize(QtCore.QSize(25, 16777215))
        self.cassetteList.setObjectName("cassetteList")
        self.gridLayout_3.addWidget(self.cassetteList, 1, 0, 1, 1)
        self.cassetteStack = QtWidgets.QStackedWidget(self.leftFrame)
        self.cassetteStack.setObjectName("cassetteStack")
        self.gridLayout_3.addWidget(self.cassetteStack, 1, 1, 1, 1)
        self.cassetteControlFrame = QtWidgets.QFrame(self.leftFrame)
        self.cassetteControlFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.cassetteControlFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cassetteControlFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cassetteControlFrame.setLineWidth(0)
        self.cassetteControlFrame.setObjectName("cassetteControlFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cassetteControlFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.cassetteControlFrame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.currentCassetteLabel = QtWidgets.QLabel(self.cassetteControlFrame)
        self.currentCassetteLabel.setObjectName("currentCassetteLabel")
        self.horizontalLayout_3.addWidget(self.currentCassetteLabel)
        self.loadButton = QtWidgets.QPushButton(self.cassetteControlFrame)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_3.addWidget(self.loadButton)
        self.gridLayout_3.addWidget(self.cassetteControlFrame, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.sampleFrame = QtWidgets.QFrame(Form)
        self.sampleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sampleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sampleFrame.setObjectName("sampleFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.sampleFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.metaDataText = QtWidgets.QTextEdit(self.sampleFrame)
        self.metaDataText.setReadOnly(True)
        self.metaDataText.setObjectName("metaDataText")
        self.gridLayout.addWidget(self.metaDataText, 0, 0, 1, 3)
        self.scanButton = QtWidgets.QPushButton(self.sampleFrame)
        self.scanButton.setObjectName("scanButton")
        self.gridLayout.addWidget(self.scanButton, 1, 0, 1, 1)
        self.mountButton = QtWidgets.QPushButton(self.sampleFrame)
        self.mountButton.setObjectName("mountButton")
        self.gridLayout.addWidget(self.mountButton, 1, 1, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.sampleFrame)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.sampleFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "State:"))
        self.stateLabel.setText(_translate("Form", "Unsafe"))
        self.label_4.setText(_translate("Form", "Mounted:"))
        self.currentSampleLabel.setText(_translate("Form", "None"))
        self.setupButton.setText(_translate("Form", "Setup"))
        self.scanAllButton.setText(_translate("Form", "Scan all"))
        self.label_3.setText(_translate("Form", "Current:"))
        self.currentCassetteLabel.setText(_translate("Form", "1"))
        self.loadButton.setText(_translate("Form", "Load"))
        self.scanButton.setText(_translate("Form", "Scan"))
        self.mountButton.setText(_translate("Form", "Mount"))
        self.runButton.setText(_translate("Form", "Run"))



